name: my_app
description: "A new Flutter project"

# Specify Flutter SDK version
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  shared_preferences: ^2.2.2
  web_socket_channel: ^2.4.0
  flutter_local_notifications: ^16.2.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  lottie: ^3.0.0
  glassmorphism_ui: ^0.3.0
  rive: ^0.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 