name: mujbites
description: "Food delivery app for MUJ campus"

# Specify Flutter SDK version
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  shared_preferences: ^2.2.2
  web_socket_channel: ^2.1.0
  flutter_local_notifications: ^9.1.5
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  lottie: ^3.0.0
  glassmorphism_ui: ^0.3.0
  rive: ^0.12.4
  permission_handler: ^11.0.1
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/logo.png
    - assets/images/logo_splash.png 